# Generated by Django 5.2.17 on 2026-08-07 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebooks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('initial_content', models.TextField()),
                ('revised_content', models.TextField(blank=True, null=True)),
                ('ai_rebuttal', models.TextField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notebook.notebook')),
            ],
        ),
        migrations.CreateModel(
            name='AIGeneration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_type', models.CharField(choices=[('audio_overview', 'Audio Overview'), ('presentation', 'Presentation'), ('video_overview', 'Video Overview'), ('mind_map', 'Mind Map'), ('report', 'Report'), ('flashcards', 'Flashcards'), ('quiz', 'Quiz'), ('infographics', 'Infographics'), ('data_table', 'Data Table')], max_length=50)),
                ('content', models.TextField(help_text='Stores the AI-generated output (can be text, markdown, or JSON).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='notebook.notebook')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('file', 'File'), ('link', 'Link'), ('text', 'Plain Text')], max_length=50)),
                ('content', models.TextField(help_text='Extracted text content from the source used for AI context.')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='sources/')),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='notebook.notebook')),
            ],
        ),
    ]
